force-app/main/LoanCalculations/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Tracking of an individual loan</description>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/LoanCalculations/objects/Loan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Loans can only be assigned to person accounts.</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/LoanCalculations/objects/Loan__c/fields/Loan_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Issue_Date__c</fullName>
    <label>Loan Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/LoanCalculations/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>Loan Charge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/LoanCalculations/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Charge</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanTriggerHandlerTest.cls
@isTest
public class LoanTriggerHandlerTest {

    @testSetup
    static void setupData() {
        // Insert a Person Account
        Account acc = new Account(FirstName = 'Test', LastName = 'Person', RecordTypeId = getPersonAccountRecordTypeId());
        insert acc;

        // Insert a valid Loan with term
        Loan__c loan = new Loan__c(
            Name = 'Valid Loan',
            Account__c = acc.Id,
            Address__Street__s = '123 Loan St',
            Gross_Loan_Amount__c = 10000,
            Date_Loan_Issued__c = Date.today(),
            Term__c = 12
        );
        insert loan;
    }

    @isTest
    static void createNewLoanCharges_validLoan_createsReleaseCharge() {
        // Given
        Loan__c loan = [SELECT Id FROM Loan__c WHERE Name = 'Valid Loan' LIMIT 1];

        // When
        List<Loan_Charge__c> charges = [
            SELECT Id, Charge_Type__c, Amount__c, Loan__c
            FROM Loan_Charge__c
            WHERE Loan__c = :loan.Id
        ];

        // Then
        System.assertEquals(1, charges.size(), 'A Release Charge should be created.');
        System.assertEquals('Release Charge', charges[0].Charge_Type__c);
        System.assertEquals(500, charges[0].Amount__c);
    }

    @isTest
    static void createNewLoanCharges_duplicateLoan_noAdditionalReleaseCharge() {
        // Given
        Loan__c loan = [SELECT Id, Account__c FROM Loan__c WHERE Name = 'Valid Loan' LIMIT 1];

        // When
        Loan__c newLoan = new Loan__c(
            Name = 'Second Loan',
            Account__c = loan.Account__c,
            Address__Street__s = '123 Second St',
            Gross_Loan_Amount__c = 8000,
            Date_Loan_Issued__c = Date.today(),
            Term__c = 6
        );
        insert newLoan;

        // Then
        List<Loan_Charge__c> releaseCharges = [
            SELECT Id FROM Loan_Charge__c WHERE Charge_Type__c = 'Release Charge'
        ];
        System.assertEquals(2, releaseCharges.size(), 'Each Loan should have one Release Charge only.');
    }

    @isTest
    static void createNewLoanCharges_missingDateOrTerm_skipsChargeCreation() {
        // Given
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Loan__c loan = new Loan__c(
            Name = 'Missing Info Loan',
            Account__c = acc.Id,
            Gross_Loan_Amount__c = 9000
        );
        insert loan;

        // When
        List<Loan_Charge__c> charges = [
            SELECT Id FROM Loan_Charge__c WHERE Loan__c = :loan.Id
        ];

        // Then
        System.assertEquals(0, charges.size(), 'No Release Charge should be created if Loan_Issue_Date__c or Term__c is null.');
    }

    @isTest
    static void createNewLoanCharges_invalidTerm_noCrash() {
        // Given
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Loan__c loan = new Loan__c(
            Name = 'Bad Term Loan',
            Account__c = acc.Id,
            Gross_Loan_Amount__c = 9500,
            Date_Loan_Issued__c = Date.today(),
            Term__c = null
        );
        insert loan;

        // Then
        List<Loan_Charge__c> charges = [SELECT Id FROM Loan_Charge__c WHERE Loan__c = :loan.Id];
        System.assertEquals(0, charges.size(), 'No Release Charge should be created if Term__c is invalid or null.');
    }

    // -- Helpers --
    
    // Get RecordTypeId for Person Account
    private static Id getPersonAccountRecordTypeId() {
        return [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Person Account' LIMIT 1].Id;
    }
}